<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="hesai_xt16">
  
  <xacro:property name="pole_x" value="1.2" />
  <xacro:property name="pole_y" value="0.0" />
  <xacro:property name="pole_z" value="1.2" />
  <xacro:property name="tilt_angle" value="0.52" />

  <link name="world"/>

  <link name="lidar_pole">
    <visual>
      <geometry><cylinder radius="0.05" length="${pole_z}"/></geometry>
      <origin xyz="0 0 ${pole_z/2}" rpy="0 0 0"/>
      <material name="gray"><color rgba="0.5 0.5 0.5 1"/></material>
    </visual>
    <collision>
      <geometry><cylinder radius="0.05" length="${pole_z}"/></geometry>
      <origin xyz="0 0 ${pole_z/2}" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="5.0"/>
      <origin xyz="0 0 ${pole_z/2}" rpy="0 0 0"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
    </inertial>
  </link>

  <joint name="pole_joint" type="fixed">
    <parent link="world"/>
    <child link="lidar_pole"/>
    <origin xyz="${pole_x} ${pole_y} 0" rpy="0 0 3.14159"/> </joint>

  <joint name="lidar_joint" type="fixed">
    <parent link="lidar_pole"/>
    <child link="hesai_base_link"/>
    <origin xyz="0 0 ${pole_z}" rpy="0 ${tilt_angle} 0"/>
  </joint>

  <link name="hesai_base_link">
    <visual>
      <geometry><cylinder radius="0.0515" length="0.0717"/></geometry>
      <material name="silver"><color rgba="0.7 0.7 0.7 1.0"/></material>
    </visual>
  </link>

  <joint name="sensor_joint" type="fixed">
    <parent link="hesai_base_link"/>
    <child link="hesai_lidar"/>
    <origin xyz="0 0 0.035" rpy="0 0 0"/>
  </joint>
  <link name="hesai_lidar"/>

  <gazebo reference="hesai_lidar">
    <sensor type="ray" name="hesai_xt16_sensor">
      <pose>0 0 0 0 0 0</pose>
      <visualize>false</visualize>
      <update_rate>10</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples><resolution>1</resolution>
            <min_angle>-3.14159</min_angle><max_angle>3.14159</max_angle>
          </horizontal>
          <vertical>
            <samples>16</samples><resolution>1</resolution>
            <min_angle>-0.2618</min_angle><max_angle>0.2618</max_angle>
          </vertical>
        </scan>
        <range><min>0.2</min><max>100.0</max></range> <noise><type>gaussian</type><mean>0.0</mean><stddev>0.005</stddev></noise>
      </ray>
      <plugin name="gazebo_ros_laser_controller" filename="libgazebo_ros_ray_sensor.so">
        <ros><remapping>~/out:=/hesai/pandar</remapping></ros>
        <output_type>sensor_msgs/PointCloud2</output_type>
        <frame_name>hesai_lidar</frame_name>
      </plugin>
    </sensor>
  </gazebo>
</robot>