<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="ur5_placeholder">

  <xacro:include filename="$(find ur_description)/urdf/ur_macro.xacro"/>

  <xacro:arg name="name" default="ur"/>
  <xacro:arg name="ur_type" default="ur5e"/>
  <xacro:arg name="prefix" default=""/>
  
  <xacro:arg name="sim_gazebo" default="true"/>
  <xacro:arg name="simulation_controllers" default=""/> 
  <xacro:arg name="initial_positions_file" default="$(find ur_description)/config/initial_positions.yaml"/>
  
  <xacro:arg name="safety_limits" default="false"/>
  <xacro:arg name="safety_pos_margin" default="0.15"/>
  <xacro:arg name="safety_k_position" default="20"/>

  <xacro:ur_robot
    name="$(arg name)"
    tf_prefix="$(arg prefix)"
    parent="world"
    joint_limits_parameters_file="$(find ur_description)/config/$(arg ur_type)/joint_limits.yaml"
    kinematics_parameters_file="$(find ur_description)/config/$(arg ur_type)/default_kinematics.yaml"
    physical_parameters_file="$(find ur_description)/config/$(arg ur_type)/physical_parameters.yaml"
    visual_parameters_file="$(find ur_description)/config/$(arg ur_type)/visual_parameters.yaml"
    safety_limits="$(arg safety_limits)"
    safety_pos_margin="$(arg safety_pos_margin)"
    safety_k_position="$(arg safety_k_position)"
    sim_gazebo="$(arg sim_gazebo)"
    >
    <origin xyz="0 0 0" rpy="0 0 0" />
  </xacro:ur_robot>

  <link name="world" />

  <gazebo>
    <plugin filename="libgazebo_ros2_control.so" name="gazebo_ros2_control">
      <parameters>$(arg simulation_controllers)</parameters>
    </plugin>
  </gazebo>

  <xacro:property name="tool_length" value="0.15" />
  <xacro:property name="tool_radius" value="0.02" />

  <link name="dummy_tool_link">
    <visual>
      <geometry>
        <cylinder radius="${tool_radius}" length="${tool_length}"/>
      </geometry>
      <origin xyz="0 0 ${tool_length/2}" rpy="0 0 0"/>
      <material name="Cyan">
        <color rgba="0 1 1 1.0"/>
      </material>
    </visual>
    
    <inertial>
      <mass value="0.2"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="tool0_to_dummy" type="fixed">
    <parent link="tool0"/>
    <child link="dummy_tool_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="fake_tcp_link"/>
  <joint name="dummy_to_tcp" type="fixed">
    <parent link="dummy_tool_link"/>
    <child link="fake_tcp_link"/>
    <origin xyz="0 0 ${tool_length}" rpy="0 0 0"/>
  </joint>

</robot>